import pytest
from framework.client import EngineClient
import time

@pytest.fixture
def client():
    c = EngineClient()
    assert c.connect()
    yield c
    c.disconnect()

def test_strategy_market_data(client):
    # Strategy buys/sells when spread > 0.05
    # Let's send a wide spread: Bid 100.0, Ask 100.1 (Spread = 0.1)
    client.send("MARKET_DATA|NVDA|100.0|100.1")
    time.sleep(0.1)
    msgs = client.read_all(timeout=0.2)
    
    # We should see execution reports generated by Strategy placing limits
    # and Exchange Sim picking them up.
    # Expect 2 orders to be handled since the strategy places both BUY and SELL
    exec_count = sum(1 for m in msgs if "EVT:EXEC" in m)
    assert exec_count >= 2
